name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.12' ]

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      with:
        path: .cache/audbcards
        key: audbcards

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install audio + video libraries
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --yes libsndfile1 ffmpeg mediainfo

    - name: Test building documentation
      run: |
        export AUDBCARDS_CACHE_ROOT=".cache/audbcards"
        uv run python pre-fill-cache.py
        uv run python -m sphinx docs/ docs/build/ -b html -W

    #- name: Check links in documentation
    #  run: python -m sphinx docs/ docs/build/ -b linkcheck -W
