name: Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]

    steps:
    - uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v3
      with:
        path: docs/cache
        key: datasets

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Ubuntu - install libsndfile
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends --yes libsndfile1

    # DOCS
    - name: Install docs requirements
      run: pip install -r docs/requirements.txt

    - name: Test building documentation
      run: python -m sphinx docs/ docs/build/ -b html -W

    #- name: Check links in documentation
    #  run: python -m sphinx docs/ docs/build/ -b linkcheck -W
